# Required to run your project under the correct environment.
language: php

services:
  - docker

env:
  DOCKER_COMPOSE_VERSION: 1.8.0
  COMPOSE_PROJECT_NAME: lighthouseservice

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

# Commands to be run before your environment runs.
before_script:
  - docker-compose up -d
  - docker exec -t lighthouseservice_app_1 composer install --prefer-source --no-interaction --dev
  - docker exec -t lighthouseservice_app_1 php artisan storage:setup --purge
  - docker exec -t lighthouseservice_app_1 php artisan torrents:import tests/Support/fixtures/exportdata.txt
  - sleep 10 # Wait for Eleastic Search to index torrents

# Commands you want to run that will verify your build.
script: docker exec -t lighthouseservice_app_1 vendor/bin/phpunit -c phpunit.xml

# allow_failures: Allow this build to fail under the specified environments.
# fast_finish: If your build fails do not continue trying to build, just stop.

# Customize when the notification emails are sent.
notifications:
    on_success: never
    on_failure: always