lighthouse:
  build: .
  ports:
    - "80:80"
    - "443:443"
    - "9000:9000"
  links:
    - redis:redis
    - elasticsearch:elasticsearch
  volumes:
    - ./:/var/www/App
    - ./docker/sites:/etc/nginx/conf.d
    - ./docker/log:/var/log
redis:
  image: redis
  ports:
    - "6379:6379"
elasticsearch:
  image: elasticsearch:2.3
  ports:
    - "9200:9200"
    - "9300:9300"